# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-07 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.CharField(blank=True, max_length=1024)),
                ('urlPartBeforeKeywords', models.CharField(max_length=1024)),
                ('urlPartAfterKeywords', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=1024)),
                ('image', models.CharField(blank=True, max_length=1024)),
                ('group', models.CharField(max_length=128)),
            ],
        ),
    ]
